"""UIDAI OTP providers: stub by default, licensed ASA/AUA swap-in for live.

Demo contract (mirrors the real UIDAI OTP Auth flow at a high level):

1. App collects the 12-digit Aadhaar number + explicit resident consent.
2. App (via ASA) calls UIDAI OTP Auth -> UIDAI sends the OTP by SMS to the
   Aadhaar-registered mobile and returns a transaction id (``txnId``).
3. Resident types the OTP from their phone; app sends ``txnId`` + OTP for
   verification.

``UIDAI_MODE=stub`` (default) simulates steps 2-3 in-process so the demo,
CI, and tests work offline: the OTP is generated locally and echoed via
``dev_otp`` in dev only. Set ``UIDAI_MODE=live`` plus the ASA/AUA credentials
below to route through ``LiveAsaAuaProvider``.

Live integration notes (do this with your licensed ASA):
- Mutual TLS + signed/encrypted PID block per UIDAI Auth API spec; see
  ``LiveAsaAuaProvider.request_otp`` for the exact call site to finalize.
- Never store the Aadhaar number: keep only the txn id + masked reference
  in Redis (TTL-bound); Postgres audit gets the masked reference only.
"""

import uuid

import httpx

from app.config import get_settings
from app.uidai.validation import demo_mobile_for


class StubUidaiProvider:
    """In-process UIDAI stand-in: mints a txn id + deterministic mobile hint.

    The actual OTP code is generated by the caller (hashed at rest in Redis).
    """

    async def request_otp(self, *, session_id: str, aadhaar_number: str) -> dict:
        return {
            "txn_id": f"uidai-stub-{uuid.uuid4().hex[:16]}",
            "registered_mobile": demo_mobile_for(aadhaar_number),
        }


class LiveAsaAuaProvider:
    """Licensed ASA/AUA path. Finalize URL/payload against your ASA spec."""

    def __init__(self, client: httpx.AsyncClient | None = None) -> None:
        self._client = client

    async def request_otp(self, *, session_id: str, aadhaar_number: str) -> dict:
        settings = get_settings()
        if not live_configured():
            raise RuntimeError("UIDAI live mode not configured (see UIDAI_* env vars)")
        client = self._client or httpx.AsyncClient(timeout=10.0)
        close = self._client is None
        try:
            # TODO(UIDAI): build the signed/encrypted PID block per the Auth API
            # spec with your ASA; POST to the ASA gateway, parse txnId +
            # masked mobile from the OTP response.
            resp = await client.post(
                f"{settings.uidai_base_url}/otp",
                json={
                    "aua": settings.uidai_aua_code,
                    "asa_license": settings.uidai_asa_license_key,
                    "aadhaar": aadhaar_number,
                    "session_ref": session_id,
                },
                headers={"Authorization": f"Bearer {settings.uidai_api_key}"},
            )
            resp.raise_for_status()
            body = resp.json()
            return {
                "txn_id": body["txnId"],
                "registered_mobile": body.get("maskedMobile", ""),
            }
        finally:
            if close:
                await client.aclose()


def live_configured() -> bool:
    settings = get_settings()
    return bool(
        settings.uidai_mode == "live"
        and settings.uidai_base_url
        and settings.uidai_aua_code
        and settings.uidai_asa_license_key
    )


def get_provider():
    if live_configured():
        return LiveAsaAuaProvider()
    return StubUidaiProvider()
