"""initial audit ledger schema

Revision ID: 508ab15e2977
Revises:
Create Date: 2026-10-01 18:02:15.179909

"""

import sqlalchemy as sa
from alembic import op

revision = "508ab15e2977"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "appraisals",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("session_id", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("bri", sa.Integer(), nullable=False),
        sa.Column("model_version", sa.String(length=64), nullable=False),
        sa.Column("sources", sa.JSON(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("disbursed_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_appraisals_session_id"), "appraisals", ["session_id"], unique=False)
    op.create_index(
        "ix_appraisals_session_status", "appraisals", ["session_id", "status"], unique=False
    )
    op.create_table(
        "audit_events",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("session_id", sa.String(length=64), nullable=False),
        sa.Column("event_type", sa.String(length=64), nullable=False),
        sa.Column("entity_id", sa.String(length=64), nullable=True),
        sa.Column("consent_id", sa.String(length=64), nullable=True),
        sa.Column("source_id", sa.String(length=32), nullable=True),
        sa.Column("record_count", sa.Integer(), nullable=True),
        sa.Column("model_version", sa.String(length=64), nullable=True),
        sa.Column("payload_hash", sa.String(length=64), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_audit_events_session_id"), "audit_events", ["session_id"], unique=False
    )
    op.create_table(
        "consents",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("session_id", sa.String(length=64), nullable=False),
        sa.Column("scope", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("granted_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_consents_session_id"), "consents", ["session_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_consents_session_id"), table_name="consents")
    op.drop_table("consents")
    op.drop_index(op.f("ix_audit_events_session_id"), table_name="audit_events")
    op.drop_table("audit_events")
    op.drop_index("ix_appraisals_session_status", table_name="appraisals")
    op.drop_index(op.f("ix_appraisals_session_id"), table_name="appraisals")
    op.drop_table("appraisals")
    # ### end Alembic commands ###
